sudo: required

before_install:
 - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa
 - sudo apt-get update
 - sudo apt-get install gcc-arm-none-eabi

script: 
  - cd skills18
  - make
  - make check_coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
