sudo: required

language: c

before_install:
 - git clone https://github.com/purduesigbots/pros-cli.git
 - sudo pip install -e pros-cli/

script: 
  - cd skills18
  - make


after_success:
  - bash <(curl -s https://codecov.io/bash)
