sudo: required

language: c

python: 3.5

os: osx

notifications:
    email: false

before_install:    

    - export HOMEBREW_NO_AUTO_UPDATE=1
    - brew tap SomaticLabs/gnu-arm-toolchain   

install:
    - brew install gcc-arm-none-eabi
    - git clone https://github.com/purduesigbots/pros-cli.git
    - sudo pip install -e pros-cli/
  
before_script:
    - cd skills18

script: 
    - make -j1 all
    
after_success:
  - bash <(curl -s https://codecov.io/bash)
