sudo: required

language: c

python: 3.5

dist: trusty

notifications:
    email: false

before_install:
    - sudo apt-get update
    
install:
    - sudo apt-get install gcc-arm-none-eabi
    
before_script:
    - cd skills18

script: 
    - make travis
