language: c

python: 3.5

os: osx

notifications:
    email: false

before_install:    
    - brew update
    - brew tap SomaticLabs/gnu-arm-toolchain   

install:
    - brew install gcc-arm-none-eabi
  
before_script:
    - cd skills18

script: 
    - make
