sudo: required

language: c

python: 3.5

notifications:
  email: false

before_install:
 - git clone https://github.com/purduesigbots/pros-cli.git
 - sudo pip install -e pros-cli/
 - sudo apt-get install gcc-arm-none-eabi

script: 
  - cd skills18
  - make


after_success:
  - bash <(curl -s https://codecov.io/bash)
