sudo: required

language: c

python: 3.5

notifications:
  email: false

before_install:
 - git clone https://github.com/purduesigbots/pros-cli.git
 - sudo pip install -e pros-cli/
 - sudo apt-get install gcc-arm-none-eabi
 - sudo apt-get install build-essential
 - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/gcc/x86_64-linux-gnu/4.8/


script: 
  #- which gcc
  #- gcc --version
  - find /usr/ -name "libstdc++.a"
  - cd skills18
  - make

after_success:
  - bash <(curl -s https://codecov.io/bash)
