sudo: required

language: c

python: 3.5

notifications:
   email: false

before_install:
   - git clone https://github.com/purduesigbots/pros-cli.git
   - sudo pip install -e pros-cli/
   - sudo apt-get install gcc-arm-none-eabi

   - LD_LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/4.8/:/usr/lib/gcc/i586-mingw32msvc/4.2.1-sjlj/
   - export LD_LIBRARY_PATH
   
   - LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/4.8/:/usr/lib/gcc/i586-mingw32msvc/4.2.1-sjlj/
   - export LIBRARY_PATH
   
   - PATH=$PATH:/usr/lib/gcc/x86_64-linux-gnu/4.8/:/usr/lib/gcc/i586-mingw32msvc/4.2.1-sjlj/
   - export PATH


script: 
    - echo $LD_LIBRARY_PATH
    - echo $LIBRARY_PATH
    - cd skills18
    - make -j1 all
